secrets:
    acme_email: ENC[AES256_GCM,data:ni8HQ5aBB29lzM73m+ZToTNuvv0=,iv:ABa3mlNlbjnb41JUMUIrteHgDE57M3IbftmgBQuWC08=,tag:UJHbSJDUdgE/9SmuvCYXwA==,type:str]
    webapp:
        env:
            MAPBOX_TOKEN: ENC[AES256_GCM,data:Sb5rdDANDxv11jpzDwfG1deZN/uLiEnj8zVPT8Ux3aiTVq0j/i1R695JdYpLlel4Ul+lPlVLz6Xx9SfUNGgc4eliBI8KxE2r5x5FXpJXxUs69NDFwE94mg==,iv:VvULkSWgxyZASEEZ8WTGKR+QNLy9/7bI3c8FZnRjwVI=,tag:rKClR+0hTsWONdW1rVCoLg==,type:str]
    backend:
        env:
            JWT_SECRET: ENC[AES256_GCM,data:YoTwpm04QMhrdsI/Se/2M1Cldt8=,iv:wKf2z8zM4GOm+a3ssq0uFgR2bwR06huSZnumH5Lz7aw=,tag:cVLTx1xjnkF5UhtujFXqpQ==,type:str]
            MAPBOX_TOKEN: ENC[AES256_GCM,data:on1vEP6tcmy0c0Ysu1rX1fiApf+Uii1KwTKGI7Q4gq8nnEjuNq5W7wCiNHVaQauIjIxNsGRXctWa+fIek0khEtriIhhZAaDCkYj32dyzvx+MjTx6XT2DPA==,iv:PQ/fpQbRhGwmIdWzzeqtI1mmDMcOL+vYS2MqYH5xABA=,tag:e8FJTpVxckldABIu1zRcoA==,type:str]
            #ENC[AES256_GCM,data:llx+JN8fRqwrLd2ahkmPrhPwcGIkn695l3Ox8VEs9YAR+1wpz3yujA==,iv:4Ctez8zMeqo3cpCCUVy6ZP4T1Z/myPw/FTq+++YAYbc=,tag:al/J8DLqNz6CoLl+TgUdOw==,type:comment]
            EMAIL_DEFAULT_SENDER: ENC[AES256_GCM,data:BzGnbiohu5JFT+T7KXz3Y8zZ,iv:jR5NyET7GtYWBa8EnxQwjbg+V8g8v8HbdYzBc3XcFzg=,tag:XOdJoXYZsT7F/tVx8z1+mQ==,type:str]
            SMTP_HOST: ENC[AES256_GCM,data:AmL4v9a3fvDK7uxoVifobeo3biYC0A==,iv:aUM6z/ZzHEFf0YbBz/L3R0CMhcT05IkmvIpgyzfSVa0=,tag:6im1h/v2RG8ZBFn/cvl5iA==,type:str]
            SMTP_USERNAME: ENC[AES256_GCM,data:8HQBi4gbO2DaXEBqbA+KGJeT,iv:8aQ+Y9wWqeSReqlLRBTsBy40otHvSJ3hBmP3PlGWx3k=,tag:7OpdMXw4yMUeqmSjge3Syw==,type:str]
            SMTP_PASSWORD: ENC[AES256_GCM,data:LwBsjL9gFovHiMzfp6M0ig==,iv:cRWpiRge5fS48oE77qid6naKH38vAc5M4hzY/lzEWp4=,tag:wz2UCBAo6Oa0SIRNkE3kqg==,type:str]
            SMTP_PORT: ENC[AES256_GCM,data:MGmv,iv:IFg6oEncN0ICEmw96XL4EuPKqEZ6KLwU5FJYkveMSpY=,tag:kIVXlt0o5TfhOtRVqU/c4w==,type:str]
            SMTP_IGNORE_TLS: ENC[AES256_GCM,data:ORAIWtg=,iv:6X4V3RDeYHrFdBTjsb3Ji0KWsZ2meL8ilqHNGQbcV/M=,tag:R87FgoQwqpes+0ejcOlrPg==,type:str]
            #ENC[AES256_GCM,data:wEE3/SPsZqy9LATseOZG7LsCbjG5gY4VUT/TzxhHLJqcYP5I,iv:gcOA0XiUGWq15G4zTRPZ0qZ/XYMTjr+9krbOx0dwpeY=,tag:jd8LTiVT7UQShqMR9zZUZA==,type:comment]
            SMTP_SECURE: ENC[AES256_GCM,data:FgQJCTY=,iv:M42XB6z1/BSMgVyEHcUOrMM54pm9C9y4k4wLgNhLcCs=,tag:MQoV6BcqbhYDZQMixVh8nQ==,type:str]
            #ENC[AES256_GCM,data:+yKTp8SBLIYHTFwZr/bOZYha0wqtf55wkv+YkIYRug==,iv:7Fb7ojlNPkHuk0uso7gsyLMydo1ZIm9T5hh2AH3CS/U=,tag:dt3BJmR4PZTrgn6FxYj9PQ==,type:comment]
            #ENC[AES256_GCM,data:3pl452NhIkUmqA9f5PwWPbcpcKxy535mMR8=,iv:h1nNA7UHa3fa0jFwXozDPk0h66vRLX3BZ5OH/fpKWIc=,tag:LM1ArSen8zKnHQXH3c4Gqw==,type:comment]
            #ENC[AES256_GCM,data:HTn1BzW0zV4o2vKU0jwwkuvtYY1ONTc2EeftKVY/Ex9Qgof0jFDLnYWstNToy8GZV+bcsCMZK5pgkmm1eGH48xhzT3ckiYW5oFKOKSN5bp3JsIu6kbLSxz+bZDjphQkgDSQbL4qIV7p1c2SnVA8YAOipqMNZMSmU/ex1d7pEFcEKgfeq7WEHoTUThJRa5HStXDxjHeVVfytjFdzTRWX/Mbm4ciuwNNJ/3ZCNkIw0605yBYcv3tDRtCHVmQbdlmmrESd0x09QvwEZxaw2saMxqLXI1x5wuasRpZdhpcyUPlbetrc9YcQDFRwtw4hgxuLzaSM5mSoM66bXk9AA4bfGPRQCdmqxwh9ap3RIel1Y6E+aTU9SrIoCIgKgkU+92vfaWwmZjWhG0DxfrOnsvHOKF1DWyKGn3AZHLqq5L8Yxree3nAu199O7ZUhHnGbhjEkYYqIIG2tV9mk25cGrQvE0hDnIrXkW3f9nGnMBS/R1UMDSh83fRKdQwIs425jFNWuRR1sRWJUlG1pXQ+plI36zOjCq/i+s7j4JfEm/G1avLc69WQVA7/dVOvlS+dmHR/gWGd+p0hoJ9iCFU8UKaA395/MYpgYs7w7z6JCxc4DY+vE9tcE7TVE/HTVD1+PIuFOJs5gckp6DSwzLX8XMAHZxIEooYJlRssrdJTANn+IyvFiWaQTxsVKsvC+WlTa0TwGyrISi9b9pRt2FWVpRMp4E3QGBEBjU2KBWJM1IhM+rocMJPe1Jzp+kqIKIXy1b4XVvgw6MiyB3/PkUet3jBhRntwYVZx4D2QkEylIlU7H9MocRknk0zAb8bQ9XiyZn9KciCBUIBWy2FPMrSlctlmpTl5hqBAIuKUybRCmjua1aSG6y+rFGRr0lsozX0pa5MUvgJazxfdj0Vy+7O9+G9NoJJhggA3OEGGFcv5HmkjtSESHHkE41uoZTSa/cnN2XXOg8qFPDjH1uTjAPZ3bwZcFVBuCg0OpuzDtDYwFSrmGfGCuV+87rp56mBFCoFGPexJ2VmxJm014e0SzIhwLV8gdcQAnuQFJgNGb90KAw+Daav5g3eFVaAGvNYKhsPWbVJrxoJbKCZFvk+gdT7krNdi/YoJcAsert5CjSuFnmC3r5cu68HObIbwNfSIT4fwJOSadcJiG//37eoFZyTITIMJyalRN+Y9PwR5b4d3kmhMGuOm+92J6YnrcGagPn1eXcqkXcAezoJOCvIpMqk/4dOZBXUjusSM4+BTlZ0Hg4vt+eB/siivpvuKUtywjx8yMp3dvV5W65IJCep9VBcX5XWzq0faDWsn55WPbmXKE+6NqYzoDKhCjvDKEVHKOvvjm/IsTssy1+WxhV3R4452pCGqoQZCVRvDDoZVb7auLnDZjfXjVSX+lAxNM2FoPZ4D1byIEip0KqzWBKDYXjqe//ShCHrm4IX+CAnIGD2yiEklDkXg3LuHBjkmXs4QjDCVgKLADBv1hl9n/hZ75x+KaRvea5zwkx8CEjMsLvc61CO0NMJoNqLEHEg4wE6covL+tcA/kRRzhHLRyMuPnX7IbRsDmweuaMjjWOcMA76MGwkB04JBDvPelVkeR45yGM4io81B3NfkYhhXaQV0rAPZPCLQq2emt7v8vIy8RLN59pyDOvJma1LAWRKufMjYQ6KiEOIlh2UmK7oGi73q7i5gNq5lw8wVIQmufNMvWvDLLC6cRCskuOA5GlzYfICe8rVHD/3ZioeohtecqEv8I6i/vfU76rfNYal+WimBwIJz9MByn1t82qrCRStF8WG5qO9Ky47NiR3T3cKZV60Ubh2O103oHD2fcGQKUdMYrokku13rdPNambpprEKlyKmfGX6hyfifQ4QwPdZxiZbS2WMboFvmgW4IOOYMts0SS1cEVopC/WagqhoqY7JjRDrelCzYHrftoNNZRpwbF/9EPH85qK/n77xiv46iG65fpdTCRgWVmjV4LpWBCjHo9sRqPBm/j3zyDOQfQyrHPIoRJH+/AhUzhP4OU6CfAC7Afc1k8S/VSa6P8aj7FRJu2Ovudirhlv1Ls900RezGy6M5mwsrzfgOoXui3XIdn7zcxKf5nxe44s4ANepF/zDEupalfncwiarMUdid1smMTvsM1nas9/MTv0t3iOQ5KvLcPMXWFBz5cnxOZ/CQoVVG/x5mbNKECsgf+tRSS8hiVqk9i4W37p9EIFq3Q7Ir4p8lK6EDpK1Nzv3LwQQ8GT7sG4XPlhUCbQf0PlLxXMo0U+8G4lUvhLHlTG8ZE+5B8XPL/fZIB5vBWijp3GMclxtfHXC303EYdQ5XU=,iv:UEKn+T5zo4HRtpSKULDbjq0Kts8bkgSali+GchLCLZs=,tag:xsC++UnKvu1VvnyEimSWUA==,type:comment]
            NEO4J_USERNAME: null
            NEO4J_PASSWORD: null
            REDIS_PASSWORD: null
    neo4j:
        env:
            NEO4J_USERNAME: ""
            NEO4J_PASSWORD: ""
sops:
    age:
        - recipient: age1al36hkk8can83zpxq8qyy07gpv83hdw9vchfly5f264kanz405as283a00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MjZ5RGI0YTFIbDk3MnBs
            ODN3RUg3ZVhsS1dEeDdodFJaQzg2RjFpcm1vClNzV1NwdEFwaXJnclRNVTJIbzVk
            VEc3YUV4eWJLb04valdNV216SnhtbzQKLS0tIHpuR2JGZWp0WnNUdStuL1ZLU0FK
            eGEreGNJTnU1OTgxL2ljVVRjUUxraEkKvkV7G56/GtJLbLVHvrq+rJ8npBckvww/
            Tq7/k/YmGV764d3Zb0Vs6TNJhoOvKF6sK645wrFlSzVNj51UxkhWYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1llp6k66265q3rzqemxpnq0x3562u20989vcjf65fl9s3hjhgcscq6mhnjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWTI4M202SmlhbzJnckF3
            ODZrY3ZQQkRLZmQrNmg4Uys2d0JBWWJMWkN3CmNwUi9HT2VYd0paMnJScnFxSXB0
            YThaU2RqWFdHMXczQ1VmdFdJQmJSU00KLS0tIDk4TW5DdUNJY3dnS1JGQUluaTJw
            d3ErbWdrZ2I3ZU1ZZGZBZ1JZU0lZMUEKnQHREjKUZ6a2+Es7SlLY46h4NPdeaE8c
            w4My+za7IjGSyL6HKqxSBLUS4Q79cI3iBNu8SwikocmEkqQ/DWlC6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zycwtk6dkxj6vuqhj9jw7932ythky9p3att6df4z9qasyw8v5dxquejcmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTmhYKzUyUGJnRHhjTU5m
            TVVFOGl5d3ZFYzE4U216a1YvVUlXTGFvYTM4CkZaMTcvRk1CVDJwek9TT0UvOWMr
            SWNrb0pvYTZaTHM4aGRpcG9odDhyUm8KLS0tIEkrSmc4V2c0Q0ltWkdRZWQ5NFEr
            Y1VWV0JTRjVmWUU4U1pTZkVhbTVLREEKvCxhsCX//e7XawyJG3XeCGLOUqxCx9No
            To4JGg10ciWcW0eqyP5lQfwdlECkmPapNz8gaf40DVpPDij5Nja+zA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15arcg8x6ltnsacwalvny0h2d4d4wkdmax328mw3v5vda9zm97uqshtavmr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaHh6b3hpbFJrcHl6eHl6
            MkZmNUJWSTJRUFVNOHJaYld3QWUwSy93aEFNCjZTZnNZRlJRR3VEeXROOFBmY2Qz
            SHF2bWMvdm5zNi92SUFlc2FZcFl1Y1kKLS0tIG4wYzdKTWFKaExiTVlFa0tRdzVs
            bGFuMlF6bkw2Z1lGNmZTV1R0ZEs2T0EK78at74wFk1B5OgeMSKrGLl3sNiwrzitL
            0kcMVyxfV68mpjb0Cw2WtEUo0jFmKFXi7H5FbJeoPrDG0QFvIvgfsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1khw2eps099audp3uu5s9rk07qznllh5c8a43gv5dtpnq2a7lue6qrehn5s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYXE0V2pFYnU5Slk5Nk5j
            Snh2UElZajhMZnlZTjVkcFBSMnF2VFJ6TG40ClBFQzV4SUpUZTZaSWpRdXNIdDBq
            ZHFUSG5uUHU0bXhhcEpCejh2elM1M2MKLS0tIEovMDdrUEs5blNvL3R0VGVaMVhw
            Q3V1UmU0OUtWRmRuQ1dtMFROUDF6NG8KRJRymV0GaOW7sENEqYogNK2HeArsuY8Y
            lVWepYYDoeRWwu7kmzORaEnW6G4m0F3rADfwMrQVTNvZ+1Xn/yFOXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f6mzqe0cejajzt0c7nwdjz4xvs4hjct9d8hrgj60e7unzyfd7prsn0npe5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbHhMUElKUWhFMERGVWpz
            cFRwTVovOStYNUQ4czIxR25MUzNON2ZzRmc0CjNvOGd4bmdjWHhwdEMzTzJkQU1Y
            SHJrZG1pQ3pmZnZxWXh4bjkwN3ZvVFEKLS0tIHRhVDgzUHNsMHYrV0RoWCtmR0Nl
            Tkx0VFJpN1pZam4yeTNYU1Jnb1JyR1EKJSQYyAi9ZZr+njaXV/62nshPVLtWIcLY
            pwP8ikur4tKrbyg7H+/f3+9jPsr2Jw3xxgkeS4GL+DsTwrGDEwoaiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-20T13:12:45Z"
    mac: ENC[AES256_GCM,data:SKBEENJhDdmyaFNXP5Wo757fD9yVl+fpz1wWGVGwbjoogWp97O3wtxtcHl+Q+SdK5bBHZqkc9u1VpTDap+HDgGVJDHKT2rsgewIB703nPiSUQwGzCASWzHvtsXGkfPal+WalQdCZcmfRXwm+PpMcruM6GUrkN+/xBl8Oi5+XfUM=,iv:g20Z7t8t/crRYfenroQ7gZYOC9GXQA5Xlg8SBFXKPK4=,tag:cw+rkDItzcfGM1/O0xa3VA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
